name: build_all
run-name: Compile Molybdenum and Datagen
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup clang++ for x64
        uses:  egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Compile Molybdenum
        run: make
      - name: Benchmarking
        run: build/Molybdenum bench
      - name: Compile Datagen
        run: make datagen
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup clang++ for x64
        uses:  egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Compile Molybdenum
        run: |
          make
          cd build
          ren Molybdenum Molybdenum.exe
      - name: Benchmarking
        run: build/Molybdenum bench
      - name: Upload Molybdenum (Win x64)
        uses: actions/upload-artifact@v4
        with:
          name: Molybdenum-${{ github.sha }}.exe
          path: build/Molybdenum.exe
          retention-days: 3
      - name: Compile Datagen
        run: make datagen
